# Generated by Django 2.2.6 on 2019-10-29 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystorage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='bodt',
            new_name='body',
        ),
    ]
